version: '3'

services:
  bot:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    command: python ./bot.py
    depends_on:
      - local_db
    networks:
      - telegram
    restart: always

  local_db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./db.env

    networks:
      - telegram
    restart: always


volumes:
  postgres_data:

networks:
  telegram:
    driver: bridge
